id: hl7.fhir.us.registry-protocols
canonical: http://hl7.org/fhir/us/registry-protocols
name: FHIRRegistryProtocolsIG
title: Protocols for Clinical Registry Extraction and Data Submission (CREDS) IG
status: draft
version: 1.0.0-ballot
fhirVersion: 4.0.1
copyrightYear: 2022+
releaseLabel: STU1

publisher:
  - name: Clinical Interoperability Council
  - url: http://hl7.org/Special/committees/cic
  - email: cic@lists.hl7.org
contact:
  - name: Clinical Interoperability Council
    telecom:
      - system: url
        value: http://hl7.org/Special/committees/cic/index.cfm
  - name: David Pyke
    telecom:
      - system: email
        value: mailto:David.Pyke@pointclickcare.com

description: The IG demonstrates a process and workflow to support the needs of clinical registries to define how registry submissions can be automatically extracted from multiple data sources and combined into a registry submission.
jurisdiction: urn:iso:std:iso:3166#US "United States of America"
dependencies:
  hl7.fhir.us.core: 5.0.1
parameters:
  show-inherited-invariants: false
  path-expansion-params: '../../exp-params.json'
  jira-code: "fhir-registry-protocols-ig"
pages:
  index.md:
    title: Home
  introduction.md:
    title: Introduction and Scope
  overview.md:
    title: Overview
  use_cases.md:
    title: Use Cases
  Architecture_and_Implementation.md:
    title: Architecture
  security_considerations.md:
    title: Security Considerations
  actors.md:
    title: Actors
  technology_environment.md:
    title: Technology Environment
  transactions.md:
    title: Transactions
  transaction-CURD.md:
    title: Create/Update Registry Definitions
  transaction-SRRD.md:
    title: Search for and Retrieve Registry Submission Definitions
  transaction-CURS.md:
    title: Create/Update Registry Submission
  transaction-RRSD.md:
    title: Retrieve Registry Submission Data
  transaction-VRS.md:
    title: Validate Registry Submission
  conformance.md:
    title: IG Conformance
  profiles_and_extensions.md:
    title: Profiles and Extensions
  test_plan.md:
    title: Test Plan
  techanalysis.md:
    title: Implementation Guide Technical Analysis

menu:
  IG Home: index.html
  Contents: toc.html
  Introduction:
    Introduction and Scope: introduction.html
    Overview: overview.html
    Use Cases: use_cases.html
  Architecture & Implementation:
    Architecture: Architecture_and_Implementation.html
    Technology Environment: technology_environment.html
    Security Considerations: security_considerations.html
    Actors: actors.html
    Profiles and Extensions: profiles_and_extensions.html
  Transactions:
    Transactions: transactions.html
    Create or Update Registry Definitions: transaction-CURD.html
    Search for and Retrieve Registry Submission Definitions: transaction-SRRD.html
    Create or Update Registry Submission: transaction-CURS.html
    Retrieve Registry Submission Data: transaction-RRSD.html
    Validate Registry Submission: transaction-VRS.html
  Testing and Conformance:
    Test Plan: test_plan.html
    IG Conformance: conformance.html
  Artifact Index: artifacts.html
  Technical Analysis: techanalysis.html

resources:
  StructureDefinition/ExampleMap:
    exampleCanonical: http://hl7.org/fhir/us/registry-protocols/StructureDefinition/CREDSStructureDefinition
  StructureDefinition/ACCNCDRCathPCIDetailed:
    exampleCanonical: http://hl7.org/fhir/us/registry-protocols/StructureDefinition/CREDSStructureDefinition