id: hl7.fhir.us.fhir-registry-protocols-ig
canonical: http://hl7.org/fhir/us/fhir-registry-protocols-ig
name: FHIRRegistryProtocolsIG
title: Protocols for Clinical Registry Extraction and Data Submission (CREDS) IG
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: ci-build

publisher:
  - name: Clinical Interoperability Council
  - url: http://hl7.org/Special/committees/cic/index.cfm
  - email: cic@lists.hl7.org
contact:
  - name: Clinical Interoperability Council
    telecom:
      - system: url
        value: http://hl7.org/Special/committees/cic/index.cfm
  - name: David Pyke
    telecom:
      - system: email
        value: mailto:dpyke@ainq.com

description: TBD.
jurisdiction: urn:iso:std:iso:3166#US "United States of America"
dependencies: 
  hl7.fhir.us.core: 4.0.0

pages:
  index.md:
    title: Home
  introduction.md:
    title: Introduction
  use_cases.md:
    title: Use Cases
  Architecture_and_Implementation.md:
    title: Architecture and Implementation
  security_considerations.md:
    title: Security Considerations
  actors.md:
    title: Actors
  technology_environment.md:
    title: Technology Environment
  transactions.md:
    title: Transactions
  transaction-CURD.md:
    title: Create/Update Registry Definitions
  transaction-SRRD.md:
    title: Search for and Retrieve Registry Submission Definitions
  transaction-CURS.md:
    title: Create/Update Registry Submission
  transaction-RRSD.md:
    title: Retrieve Registry Submission Data
  transaction-VRS.md:
    title: Validate Registry Submission
  conformance.md:
    title:  IG Conformance
  profiles_and_extensions.md:
    title: Profiles and Extensions
  test_plan.md:
    title: Test Plan
  overview.md:
    title: Overview



# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  IG Home: index.html
  Contents: toc.html
  Introduction:
    Scope: introduction.html
    Use Cases: use_cases.html
  Architecture &amp; Implementation:
    Architecture: Architecture_and_Implementation.html
    Technology Environment: technology_environment.html
    Security Considerations: security_considerations.html
    Actors: actors.html
    Profiles and Extensions: profiles_and_extensions.html
  Transactions: 
    Create or Update Registry Definitions: transaction-CURD.html
    Search for and Retrieve Registry Submission Definitions: transaction-SRRD.html
    Create or Update Registry Submission: transaction-CURS.html
    Retrieve Registry Submission Data: transaction-RRSD.html
    Validate Registry Submission: transaction-VRS.html
  Testing and Conformance: 
    Test Plan: test_plan.html
    IG Conformance: conformance.html
  Artifact Index: artifacts.html

